name: MyCI_CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.7

      - name: setup Java 8
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: setup gradle
        uses: gradle/gradle-build-action@v2

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
              key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
              restore-keys: |
                gradle-${{ runner.os }}-

      - name: build with gradle
        uses: ./gradlew build

      - name: build Debug APK
        uses: ./gradlew assembleDebug

      - name: Upload Debug APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }} # Firebase App ID
          token: ${{ secrets.FIREBASE_TOKEN }}  # Firebase Authentication Token
          groups: mytesters                      # Group of testers to notify
          file: app/build/outputs/apk/debug/app-debug.apk

      - name: Send Notification to Testers Group
        env:
          FIREBASE_SERVER_KEY: ${{ secrets.FIREBASE_SERVER_KEY }}
          FIREBASE_TOPIC: Testers
          run: |
            curl -X POST -H "Authorization: key=${{ secrets.FIREBASE_SERVER_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "to": "/topics/mytesters",
                  "notification": {
                    "title": "New AceNews APK Available",
                    "body": "A new debug APK has been uploaded. Please check it out."
                  }
                }' \
            https://fcm.googleapis.com/fcm/send